# This is a basic workflow to help you get started with Actions
name: Android Build

env:
  # The name of the main module repository
  main_project_module: app

  # The name of the Play Store
  play_store_name: shareque

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "master" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          # Step 1 : see README.md file for description
          - name: Checkout
            uses: actions/checkout@v4.1.1

          # Step 2
          - name: Setup Java JDK
            uses: actions/setup-java@v4.0.0
            with:
              java-version: '17'
              distribution: 'adopt'

          - name: Change wrapper permissions
            run: chmod +x ./gradlew

          # Step 3
          # Runs a single command using the runners shell
          - name: Build with Gradle
            run: ./gradlew build

          # Set Current Date As Env Variable
          - name: Set current date as env variable
            run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

          # Set Repository Name As Env Variable
          - name: Set repository name as env variable
            run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

          # Step 4
          # Run Tests Build
          - name: Run gradle tests
            run: ./gradlew test

          # Step 5
          # Create Bundle AAB Release
          # Noted for main module build [main_project_module]:bundleRelease
          - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
            run: ./gradlew ${{ env.main_project_module }}:bundleRelease
          # Above step is required for creating signed bundle
          # Step 5
          # Create APK Release
          #- name: Build Release APK project (APK) - ${{ env.main_project_module }} module
           # run: ./gradlew assemble

          # Step 6 : Creating signed bundle
          - name: Sign AAB
            id: sign
            uses: r0adkll/sign-android-release@v1
            with:
              #check with your signed build path and then use it in my case is located at 'app\release' other case the path is 'app/build/outputs/bundle/release'
              releaseDirectory: ${{ env.main_project_module }}/build/outputs/bundle/release
              signingKeyBase64: ${{ secrets.SIGNING_KEY }}
              alias: ${{ secrets.ALIAS }}
              keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
              keyPassword: ${{ secrets.KEY_PASSWORD }}

          - name: Sign APK
            id: sign_apk
            uses: r0adkll/sign-android-release@v1
            with:
              #check with your signed build path and then use it in my case is located at 'app\release' other case the path is 'app/build/outputs/bundle/release'
              releaseDirectory: ${{ env.main_project_module }}/build/outputs/apk/release
              signingKeyBase64: ${{ secrets.SIGNING_KEY }}
              alias: ${{ secrets.ALIAS }}
              keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
              keyPassword: ${{ secrets.KEY_PASSWORD }}
            env:
              # Setting build tool version will reduce error if we comment this line it will through exception for build tool version 29.*
              BUILD_TOOLS_VERSION: "34.0.0"

          # Step 7
          # Noted For Output [main_project_module]/build/outputs/bundle/release/
          - name: Upload AAB (App Bundle) Release - ${{ env.repository_name }}
            uses: actions/upload-artifact@v4
            with:
              name: ${{ env.date_today }} - ${{ env.play_store_name }} - ${{ env.repository_name }} - App bundle(s) AAB release generated
              path: ${{ env.main_project_module }}/build/outputs/bundle/release/

          # Noted For Output [main_project_module]/build/outputs/apk/release/
          - name: Upload APK Release - ${{ env.repository_name }}
            uses: actions/upload-artifact@v4
            with:
              name: ${{ env.date_today }} - ${{ env.play_store_name }} - ${{ env.repository_name }} - APK(s) release generated
              path: ${{ env.main_project_module }}/build/outputs/apk/release/


